[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/public"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/api/:splat"
  status = 200
  force = true
